
he8us_feedback_homepage:
    path:     /feedback/{status}
    defaults: { _controller: "He8usFeedbackBundle:FeedbackAdmin:index", status: 'none' }

he8us_feedback_inbox:
    path:     /feedback/inbox
    defaults: { _controller: "He8usFeedbackBundle:Feedback:inbox" }

he8us_feedback_delete:
    path:     /feedback/remove/{id}
    defaults: {_controller: "He8usFeedbackBundle:FeedbackAdmin:delete" }
    methods: [DELETE]

he8us_feedback_mark_read:
    path:     /feedback/mark/read/{id}
    defaults: {_controller: "He8usFeedbackBundle:FeedbackAdmin:markAs", type: 'read' }

he8us_feedback_mark_done:
    path:     /feedback/mark/done/{id}
    defaults: {_controller: "He8usFeedbackBundle:FeedbackAdmin:markAs", type: 'done' }

he8us_feedback_reply:
    path:     /feedback/reply/{id}
    defaults: {_controller: "He8usFeedbackBundle:FeedbackAdmin:reply"}
