He8us\FeedbackBundle\Entity\Feedback:
    repositoryClass: He8us\FeedbackBundle\Entity\FeedbackRepository
    type: entity
    table: feedback
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: integer
            length: 1
        senderIp:
            type: string
            length: 255
        referrer:
            type: string
            length: 255
        loggedUser:
            type: integer
            length: 11
            nullable: true
        email:
            type: string
            length: 255
        body:
            type: text
        screenshot:
            type: text
            nullable: true
        category:
            type: integer
            nullable: false

        deleted:
            type: boolean
            options:
                default: false
            nullable: true
    lifecycleCallbacks: {  }
