
he8us_feedback_new:
    path:     /feedback/new
    defaults: { _controller: "He8usFeedbackBundle:Feedback:new" }

he8us_feedback_admin:
    resource: "@He8usFeedbackBundle/Resources/config/routing/admin.yml"
    prefix: /admin
