services:
  he8us_feedback.extension:
    class: He8us\FeedbackBundle\Twig\FeedbackExtension
    arguments: ["@form.factory", "@twig", "@he8us_feedback.category_service"]
    tags:
      - { name: twig.extension }


  he8us_feedback.category_service:
    class: He8us\FeedbackBundle\Service\CategoryService
    arguments: ["@doctrine"]

  he8us_feedback.feedback_service:
    class: He8us\FeedbackBundle\Service\FeedbackService
    arguments: ["@doctrine"]
